export const timezones = [
    { name: 'UTC' },
    { name: 'Europe/London' },
    { name: 'Europe/Berlin' },
    { name: 'Europe/Moscow' },
    { name: 'Asia/Dubai' },
    { name: 'Asia/Karachi' },
    { name: 'Asia/Almaty' },
    { name: 'Asia/Bangkok' },
    { name: 'Asia/Singapore' },
    { name: 'Asia/Tokyo' },
    { name: 'Australia/Sydney' },
    { name: 'Pacific/Noumea' },
    { name: 'Pacific/Fiji' },
    { name: 'Atlantic/Azores' },
    { name: 'America/Noronha' },
    { name: 'America/Argentina/Buenos_Aires' },
    { name: 'America/Santiago' },
    { name: 'America/New_York' },
    { name: 'America/Mexico_City' },
    { name: 'America/Denver' },
    { name: 'America/Los_Angeles' },
    { name: 'America/Anchorage' },
    { name: 'Pacific/Honolulu' },
    { name: 'Pacific/Midway' }
  ];